version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_DNS_API_TOKEN={{CLOUDFLARE_TOKEN}}
      - CF_ZONE_API_TOKEN={{CLOUDFLARE_TOKEN}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`{{TRAEFIK_HOST}}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users={{TRAEFIK_AUTH}}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`{{TRAEFIK_HOST}}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main={{DOMAIN}}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{DOMAIN}}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  traefik:
    external: true
